# Generated by Django 5.1.5 on 2025-01-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
