# Generated by Django 5.0.3 on 2025-01-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
