# Generated by Django 5.0.3 on 2025-01-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appApi', '0006_delete_package'),
        ('appAuth', '0010_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_folder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAuth.profile')),
            ],
        ),
    ]
