# Generated by Django 5.0.3 on 2025-01-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0010_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='package',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Withdraw',
        ),
    ]
