# Generated by Django 5.1.5 on 2025-01-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
    ]
