# Generated by Django 5.1.5 on 2025-01-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0013_remove_package_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='slider_image_folder')),
                ('image2', models.ImageField(upload_to='slider_image_folder')),
                ('image3', models.ImageField(upload_to='slider_image_folder')),
            ],
        ),
    ]
