# Generated by Django 5.1.5 on 2025-01-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0015_deposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
