# Generated by Django 5.1.5 on 2025-01-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0017_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='profit_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
