# Generated by Django 5.1.5 on 2025-01-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0019_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='b_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
