# Generated by Django 5.1.5 on 2025-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0020_withdraw_b_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_taka',
            field=models.IntegerField(default=0),
        ),
    ]
