# Generated by Django 5.1.5 on 2025-01-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0021_package_price_taka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='profit_start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
