# Generated by Django 5.1.5 on 2025-01-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0022_alter_deposit_profit_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='profit_start_date',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
