# Generated by Django 5.1.5 on 2025-01-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0023_remove_deposit_profit_start_date_withdraw_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='tran_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='b_number',
            new_name='bkash_number',
        ),
    ]
