# Generated by Django 5.1.5 on 2025-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0024_rename_tran_id_deposit_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='send_number',
            field=models.CharField(default='***********', max_length=20),
        ),
    ]
