# Generated by Django 5.1.5 on 2025-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0025_deposit_send_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='package_name',
            field=models.CharField(default='Package Name', max_length=100),
        ),
    ]
