# Generated by Django 5.1.5 on 2025-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0026_deposit_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
