# Generated by Django 5.1.5 on 2025-01-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+880 1609999999', max_length=15, unique=True),
        ),
    ]
