# Generated by Django 5.1.5 on 2025-01-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0003_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
