# Generated by Django 5.1.5 on 2025-01-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
