# Generated by Django 5.1.5 on 2025-01-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0006_remove_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
