# Generated by Django 5.1.5 on 2025-01-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0007_remove_profile_about_remove_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_folder'),
        ),
    ]
