# Generated by Django 5.0.3 on 2025-01-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0009_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=100),
        ),
    ]
