# Generated by Django 5.0.3 on 2025-01-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0011_remove_deposit_profile_remove_package_profile_and_more'),
        ('appAuth', '0012_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
