# Generated by Django 5.0.3 on 2025-01-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0013_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
