# Generated by Django 5.1.5 on 2025-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0015_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bkash_number',
            field=models.CharField(default='01*********', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
